import { Button } from '@/components/ui/button'
import {
  DropdownMenu,
  DropdownMenuContent,
  DropdownMenuItem,
  DropdownMenuTrigger,
} from '@/components/ui/dropdown-menu'
import { FileDown, FileText } from 'lucide-react'

import { useExportQuotation } from '../hooks/use-export'
import type { ExportFormat, ExportLanguage, Quotation } from '../types'

interface Props {
  quotation: Quotation
}

// Only shown when status === 'approved'. PDF/DOCX are generated by the
// backend (gotenberg for PDF, native docx for Word) and returned as a
// signed, short-lived download URL that the browser opens in a new tab.
// Word export is bilingual-only in M1 (docx renderer doesn't branch on
// language yet); PDF supports all three.
export function QuotationExportActions({ quotation }: Props) {
  const exportMut = useExportQuotation(quotation.id)
  if (quotation.status !== 'approved') return null

  const trigger = (format: ExportFormat, language: ExportLanguage) =>
    exportMut.mutate({ format, language })
  const disabled = exportMut.isPending

  return (
    <div className='flex gap-2'>
      <DropdownMenu>
        <DropdownMenuTrigger asChild>
          <Button variant='default' disabled={disabled}>
            <FileDown className='mr-2 h-4 w-4' />
            导出 PDF / Export PDF
          </Button>
        </DropdownMenuTrigger>
        <DropdownMenuContent>
          <DropdownMenuItem onClick={() => trigger('pdf', 'bilingual')}>
            中英双语 / Bilingual
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => trigger('pdf', 'zh')}>
            仅中文 / Chinese only
          </DropdownMenuItem>
          <DropdownMenuItem onClick={() => trigger('pdf', 'en')}>
            仅英文 / English only
          </DropdownMenuItem>
        </DropdownMenuContent>
      </DropdownMenu>

      <Button
        variant='outline'
        disabled={disabled}
        onClick={() => trigger('docx', 'bilingual')}
      >
        <FileText className='mr-2 h-4 w-4' />
        导出 Word / Export Word
      </Button>
    </div>
  )
}
